targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true
        generate_for:
          - lib/domain**/*.dart
          - lib/application**/*.dart
